export { default as MarketingShell } from "./MarketingShell";
export { default as PageHero } from "./PageHero";
export { default as PageCta } from "./PageCta";
export { default as FeatureGrid } from "./FeatureGrid";
export { default as ContentSection } from "./ContentSection";
export { default as ProductPageTemplate } from "./ProductPageTemplate";
export { default as LegalDocument, LegalHeading, LegalParagraph, LegalQuote } from "./LegalDocument";
export { renderLegalLines } from "./renderLegalLines";
export type { FeatureCard } from "./FeatureGrid";
export type { ProductPageProps } from "./ProductPageTemplate";
