import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Proof of Concept Agreement",
  description:
    "Jataka Proof of Concept (POC) Agreement for 14-day free pilot testing with zero data retention and automatic data deletion.",
  alternates: {
    canonical: "https://jataka.io/poc-agreement",
  },
  openGraph: {
    title: "Proof of Concept Agreement | Jataka",
    description:
      "Jataka Proof of Concept (POC) Agreement for 14-day free pilot testing with zero data retention and automatic data deletion.",
    url: "https://jataka.io/poc-agreement",
    siteName: "Jataka",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "Jataka" }],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Proof of Concept Agreement | Jataka",
    description:
      "Jataka Proof of Concept (POC) Agreement for 14-day free pilot testing with zero data retention and automatic data deletion.",
    images: ["/og-image.png"],
  },
  robots: { index: true, follow: true },
};

const POC_TEXT = `PROOF OF CONCEPT (POC) AGREEMENT
Last Updated: April 13, 2026
This Proof of Concept Agreement ("POC Agreement") is entered into by and between Jataka Inc. ("Jataka") and the customer identified in the signup form ("Customer") for the purpose of testing Jataka's DevSecOps and Runtime Governance platform.
1. POC TERM
1.1 Duration. The POC shall commence on the Effective Date (date of Customer's acceptance) and continue for a period of fourteen (14) days ("POC Term"), unless terminated earlier in accordance with this Agreement.
1.2 Automatic Termination. This POC Agreement shall automatically terminate upon the earlier of: (a) expiration of the POC Term, or (b) execution of a Master Subscription Agreement and Order Form between the parties.
2. SCOPE OF SERVICES
2.1 Free Access. During the POC Term, Customer shall have free access to Jataka's standard DevSecOps and Runtime Governance Services for testing purposes only.
2.2 Usage Limitations. Access during the POC Term is limited to Customer's non-production (sandbox) Salesforce environments. Customer agrees not to use the Services for production workloads during the POC Term.
2.3 Support. Jataka will provide standard Slack support during the POC Term to assist with setup and troubleshooting.
3. DATA PROTECTION AND PROCESSING
3.1 Data Processing Agreement. The processing of Customer Data during the POC Term shall be governed by Jataka's Data Processing Agreement located at jataka.io/dpa, which is hereby incorporated by reference.
3.2 Zero Data Retention. Jataka maintains zero data retention policies with all AI Sub-processors. Customer's proprietary code and metadata are processed ephemerally and are never used to train third-party AI models.
3.3 Sandbox-Only Access. Customer grants Jataka OAuth access strictly to Customer's sandbox environments (Staging, Integration, or Developer orgs). Customer agrees not to provide access to production Salesforce orgs during the POC Term.
4. DATA DELETION
4.1 Automatic Deletion. Upon expiration or termination of this POC Agreement, Jataka will automatically delete all Customer Data from its systems within thirty (30) days, unless Customer executes a Master Subscription Agreement with Jataka prior to such deletion.
4.2 No Data Retention. If Customer does not purchase a paid subscription after the POC Term, all Customer Data will be permanently deleted. Jataka will not retain any Customer Data for marketing, analytics, or any other purpose.
5. INTELLECTUAL PROPERTY
5.1 Jataka Property. Jataka retains all rights, title, and interest in the Services, underlying technology, and all associated intellectual property.
5.2 Customer Data. Customer retains all rights, title, and interest in Customer Data.
5.3 Output Ownership. Subject to Customer's compliance with this Agreement, Customer shall own all Output (code snippets, metadata modifications, Pull Requests) generated by the Services during the POC Term.
6. CONFIDENTIALITY
6.1 Mutual Confidentiality. Each party agrees to keep the other party's Confidential Information confidential and to use it only for the purposes of this POC.
6.2 Definition. "Confidential Information" includes all non-public information disclosed by either party, including Customer Data, source code, and Jataka's platform technology.
7. DISCLAIMER OF WARRANTIES
7.1 "AS IS" Basis. The Services are provided "AS IS" and "AS AVAILABLE" during the POC Term. Jataka makes no warranties of any kind, whether express, implied, statutory, or otherwise.
7.2 Advisory Nature. Customer acknowledges that Jataka is an automated DevSecOps and static analysis tool. AI agents may produce false positives, false negatives, or logically flawed code. Customer is solely responsible for reviewing, testing, and verifying any code or suggestions before deployment.
8. LIMITATION OF LIABILITY
8.1 Cap on Liability. Jataka's aggregate liability arising out of this POC Agreement shall not exceed $100.00.
8.2 Exclusion of Consequential Damages. In no event shall Jataka be liable for any lost profits, revenues, data, or for any indirect, special, incidental, consequential, or punitive damages.
9. CUSTOMER INDEMNIFICATION
9.1 Customer Indemnification. Customer will defend Jataka against any claim made by a third party alleging that Customer Data infringes the rights of that third party or violates applicable laws, and will indemnify Jataka for any damages and costs finally awarded.
10. NO OBLIGATION TO PURCHASE
10.1 No Commitment. This POC Agreement does not obligate Customer to purchase any subscription or services from Jataka after the POC Term.
10.2 No Commitment. Jataka is not obligated to offer Customer a subscription or to continue providing Services after the POC Term.
11. TRANSITION TO PAID SUBSCRIPTION
11.1 MSA Required. If Customer wishes to continue using the Services after the POC Term, Customer must execute Jataka's Master Subscription Agreement and an Order Form.
11.2 Data Continuation. If Customer executes a Master Subscription Agreement prior to data deletion, Customer Data may be retained and transferred to the paid subscription in accordance with the MSA and DPA.
12. GENERAL PROVISIONS
12.1 Governing Law. This POC Agreement shall be governed by the laws of the State of Delaware, without regard to its conflict of laws principles.
12.2 Entire Agreement. This POC Agreement, together with the incorporated DPA, constitutes the entire agreement between the parties.
12.3 Amendment. No amendment to this POC Agreement shall be effective unless in writing and signed by both parties.
13. ACCEPTANCE
13.1 By clicking "Accept" or by accessing or using the Services during the POC Term, Customer agrees to be bound by this POC Agreement and the incorporated DPA.
13.2 Effective Date. This POC Agreement becomes effective on the date Customer accepts these terms or first accesses the Services.`;

export default function POCAgreementPage() {
  const lines = POC_TEXT.split("\n");

  return (
    <div className="min-h-screen bg-[#FAF8F3] text-[#1a1a1a]">
      <header className="fixed top-0 left-0 right-0 z-[200] h-[64px] bg-[#FAF8F3]/90 backdrop-blur-[14px] border-b border-[#1a1a1a]/10 px-[24px] md:px-[48px] flex items-center justify-between">
        <Link
          href="/"
          className="text-[13px] font-semibold uppercase tracking-[1.6px] text-[#666] hover:text-[#1a1a1a] transition-colors"
        >
          ← Back to Home
        </Link>
        <Link
          href="/book-pilot"
          className="bg-[#FF2424] text-white px-[16px] py-[8px] text-[11px] font-semibold uppercase tracking-[1.4px] rounded-[4px] hover:bg-[#d91f1f] transition-colors"
        >
          Book Demo
        </Link>
      </header>

      <main className="mx-auto max-w-[980px] px-[24px] md:px-[40px] pt-[112px] pb-[80px]">
        <section className="mb-[24px] rounded-[12px] border border-[#1a1a1a]/10 bg-white p-[24px] md:p-[36px]">
          <p className="inline-flex items-center gap-[8px] bg-[#FF2424]/10 border border-[#FF2424]/20 px-[12px] py-[5px] text-[11px] font-bold uppercase tracking-[2px] text-[#FF2424]">
            Legal
          </p>
          <h1 className="mt-[16px] font-archivo text-[clamp(30px,5vw,48px)] leading-[1] tracking-[-1.2px] uppercase">
            Proof of Concept Agreement
          </h1>
          <p className="mt-[12px] text-[14px] text-[#666]">
            14-Day Free Pilot with Zero Data Retention
          </p>
        </section>

        <section className="rounded-[12px] border border-[#1a1a1a]/10 bg-white p-[22px] md:p-[36px]">
          <div className="space-y-[12px]">
            {lines.map((line, idx) => {
              if (!line.trim()) {
                return <div key={idx} className="h-[2px]" />;
              }

              if (/^\d+\.\s[A-Z]/.test(line) || /^\d+\.\d+\.\s[A-Z]/.test(line)) {
                return (
                  <h2
                    key={idx}
                    className="pt-[12px] font-archivo text-[20px] md:text-[24px] leading-[1.1] tracking-[-0.5px] uppercase"
                  >
                    {line}
                  </h2>
                );
              }

              if (/^\d+\.\d+\s/.test(line) || /^\d+\.\d+\.\d+\s/.test(line)) {
                return (
                  <p
                    key={idx}
                    className="text-[14px] md:text-[15px] leading-[1.85] text-[#2c2c2c]"
                  >
                    <span className="font-semibold text-[#1a1a1a]">{line.slice(0, line.indexOf(" ") + 1)}</span>
                    {line.slice(line.indexOf(" ") + 1)}
                  </p>
                );
              }

              if (line.startsWith('"')) {
                return (
                  <p
                    key={idx}
                    className="pl-[12px] border-l-2 border-[#1a1a1a]/10 text-[14px] md:text-[15px] leading-[1.85] text-[#2c2c2c]"
                  >
                    {line}
                  </p>
                );
              }

              if (line.includes(":") && line.length < 100 && !line.includes("http")) {
                const parts = line.split(":");
                if (parts.length === 2) {
                  return (
                    <p
                      key={idx}
                      className="text-[14px] md:text-[15px] leading-[1.85] text-[#2c2c2c]"
                    >
                      <span className="font-semibold text-[#1a1a1a]">{parts[0]}:</span>
                      {parts[1]}
                    </p>
                  );
                }
              }

              // Make URLs clickable
              if (line.includes("jataka.io/")) {
                const urlMatch = line.match(/(jataka\.io\/[a-zA-Z0-9\-]+)/);
                if (urlMatch) {
                  const url = urlMatch[0];
                  const beforeUrl = line.split(url)[0];
                  const afterUrl = line.split(url)[1] || "";
                  return (
                    <p key={idx} className="text-[14px] md:text-[15px] leading-[1.85] text-[#2c2c2c]">
                      {beforeUrl}
                      <Link href={`/${url.split('/')[1]}`} className="text-[#FF2424] underline hover:text-[#d91f1f]">
                        {url}
                      </Link>
                      {afterUrl}
                    </p>
                  );
                }
              }

              return (
                <p key={idx} className="text-[14px] md:text-[15px] leading-[1.85] text-[#2c2c2c]">
                  {line}
                </p>
              );
            })}
          </div>
        </section>
      </main>
    </div>
  );
}
